### ISSUE TITLE
Add DNS.WATCH

### ISSUE THREAD

**Issue by Angristan** [privacytools-io/privacytools.io#16]
As [CloudNS should be removed](https://github.com/privacytools-io/privacytools.io/pull/5), I suggest to add [DNS.WATCH](https://dns.watch/index) to replace it.

It claims to be free, uncensored, and logless. I monitored them for months, and as I can see they have a good uptime.

They're hosted in germany, though.

**Comment by Shifterovich** [comment]
Germany isn't optimal, but much better than Australia. Seems nice to me.

**Comment by Angristan** [comment]
There is also [FDN's servers](https://www.fdn.fr/actions/dns/). FDN is a french associate ISP since 1992. They  work against the internet censorship.

**Comment by Shifterovich** [comment]
@Angristan Could you write description for DNS.WATCH and replace CloudNS with it?

**Comment by Angristan** [comment]
Done :)

**Comment by Shifterovich** [comment]
Fixed: #20

**Comment by andreimaxim** [comment]
Just out of curiosity, why is DNS.WATCH recommended? As far as I can tell, it's owned by a German "media and IT" agency so it doesn't look like it's focused towards privacy in any way. Yes, they do say on their site that it's a "no logging" policy but how credible is that information?

**Comment by kewde** [comment]
@andreimaxim I merely compare one-to-one, and in the case of cloudns vs dns.watch I preferred the latter.
If anyone comes up with a security/privacy focused DNS provider that has a better and even proven track record and provides DNSSEC, then I'm all ears for considering that one instead.

But in absolute terms it's definitely an upgrade from cloudns. 

As for the "no logging" discussion, it is one not worth having. You can never guarantee that without access to the servers. There are however entities whom I believe to be less likely to log due the legal framework but that is out of the scope of your question.

**Comment by Angristan** [comment]
Nothing to add.
